### PR TITLE
Add path color context menu

### PR DESCRIPTION
**Pull request by SteveRussell33**
**Note:** this PR requires merging of the Dark Room PR made previously because of a ``module`` pointer check in ``void drawLayer``

### CODE REVIEW

**Review by epadilla — APPROVED** [review]
Oh nice! Is this an option often offered by modules? I like it!

**Comment by SteveRussell33** [comment]
People do like their different color schemes! lol 
Makes sense to have a palette to choose from with the addition of "dark room" support. 
Could even make it a color slider in the menu instead for a greater range of colors. Thoughts?

**Comment by epadilla** [comment]
I like the use of the standard colors – I prefer this to slider.

**Comment by epadilla** [comment]
Oh looks like there's a build break. Oddly, not getting it locally on my machine though. I can look into it later.

https://github.com/epadilla/patina/actions/runs/6594023506

**Comment by SteveRussell33** [comment]
Oh that's because ``#include<array>`` is missing. Same here, I don't get that build failure locally.

**Pull request merged**
